### ISSUE TITLE
About data and dataset creation

### ISSUE THREAD

**Issue by Leerw** [Gorilla-Lab-SCUT/DualPoseNet#2]
Like the title, where is the data and how to create the dataset used in the code?

**Comment by liguowei666** [comment]
I have the same problem, can you tell how to use dataset?

**Comment by PnthrLeo** [comment]
Thank you so much for the great paper and the nice clean code with detailed README.md!

It is clear how to evaluate and test your model. However, I cannot fully understand how to prepare train data (e.g. REAL275) for training your model.
I saw .npz files in your _**Fetcher class**_. Are those were created by yourself? Or were it downloaded from somewhere?

Thank you in advance!

**Comment by dedoogong** [comment]
I have met the same problem!! Please make this clear for us~!

**Comment by JiehongLin** [comment]
Thank you for reminding~ I have included the code in `provider/training_data_prepare.py`. Please follow the guidance to prepare  training data.

**Comment by dedoogong** [comment]
thank you! but can you upload one more file " align_utils.py" ?
The file seems to be modified little bit from the original version in SPD net repo.

**Comment by JiehongLin** [comment]
The code is originated from NOCS (https://github.com/hughw19/NOCS_CVPR2019/blob/master/utils.py).
