### ISSUE TITLE
how to run  evaluation after  train?

### ISSUE THREAD

**Issue by dedoogong** [Gorilla-Lab-SCUT/DualPoseNet#3]
I think I shuld generate result pkl files by running Testing 2 times( w/o refined, w/ refined version) and then your code will generate the pkl files and then I should run eval.py. right?

**Comment by JiehongLin** [comment]
You could only run testing, since evaluation is also included in this procesure ( L65 in `main.py`).

Besides, you could directly run `python main.py --phase test_refine_encoder --dataset REAL275`  for the refined version, without running 2 times.
